### ISSUE TITLE
Structured output parsing

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#120]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Sometimes a user wants structure the output of the agent, e.g like JSON etc. 

Would be nice to create an API for this where the user can post their schema. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by arashilmg** [comment]
Without This, I need to use another runtime/app/framework (e.x. Langchain Output Parser) to just parse the output to structured JSON. Because any real-life integration I can think of requires a JSON structured input/outpu.

Basically, without this feature, It might make more sense to just ignore this project totally and just use everything in one single runtime (e.x. using Langchain SDK)


_Thank you @homanp for this great project though_

**Comment by arashilmg** [comment]
This feature ideally should support a refine/retry process as well, something like auto-fixer:
https://python.langchain.com/docs/modules/model_io/output_parsers/output_fixing_parser

**Comment by homanp** [comment]
> Without This, I need to use another runtime/app/framework (e.x. Langchain Output Parser) to just parse the output to structured JSON. Because any real-life integration I can think of requires a JSON structured input/outpu.
> 
> Basically, without this feature, It might make more sense to just ignore this project totally and just use everything in one single runtime (e.x. using Langchain SDK)
> 
> 
> _Thank you @homanp for this great project though_

@arashilmg I agree with the output parsing. This is something we are actively working on and will release in the next version of Superagent (v0.1.0). Although it will not be based on LangChain.

With regards to using LangChain over Superagent there are ultimately several factors a user needs to consider when choosing any framework for a project. Superagent is more focused on provisioning of agents in production use cases. I'm in tight dialogue with LangChain core team as I believe it to be a fundamental part of the stack. 

But we serve different user segments and purposes. 

Thank you for you kind words, our goal is to build something useful an enable any developer to integrate AI features in any app. 

🙏🙏🙏
