### ISSUE TITLE
Very confusing to setup

### ISSUE THREAD

**Issue by mberman84** [homanp/superagent#149]
### What piece of documentation is affected?

the onboarding script is not clear and there's no documentation

for example, it asks for a database_url....what kind of database? 

migration URL? where would I get that? 

shadow URL? i don't even know what that is. 

then it asks for "Please provide the value for #"

can you help me understand what values you're looking for for all of these?

### What part(s) of the article would you like to see updated?

onboarding documentation

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@mberman84 you are 💯 % correct. I will make an update to the `README` to make this more clear. 

DATABASE_URL kan be any pooled db connection string that is supported by `Prisma`. I myself use [supabase.com](https://supabase.com)

The `DATABASE_MIGRATION_URL` is also a connection to the DB but non-pooled.

`DATABASE_SHADOW_URL` is for those who use: https://neon.tech/

Also I'm recording a tutorial tonight which you can watch.

**Comment by mberman84** [comment]
Cool, thanks. I plan to record a tutorial as well if I can get this working :)

**Comment by homanp** [comment]
> Cool, thanks. I plan to record a tutorial as well if I can get this working :) 

I update the README with descriptions and updated the bash script. Get back to me if you can't get it working .

**Comment by mrahmadt** [comment]
In README, for the Docker installation
```
The main docker-compose.yml file will start up the API and a Postgres DB in docker
```

if docker-compose will deploy Postgres, what should I add to database_url?
