### ISSUE TITLE
Add integration to CRM - HighLevel

### ISSUE THREAD

**Issue by rapidstartup** [homanp/superagent#151]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Recently Hubspot was added. In the same vein, let's add an integration for HighLevel.
This is the API documentation
https://highlevel.stoplight.io/docs/integrations/0443d7d1a4bd0-overview

OAuth2.0 token required.
They have a marketplace for integration automation. Happy to help.

I recommended adding "add contacts" and "add conversation"
This is a Whitelabel CRM so the network affects here will be great

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@rapidstartup we've just released support for `Airbyte` loaders and I'm gonna check if Highlevel is listed there before jumping on this.

**Comment by Fepvannak** [comment]
https://youtube.com/@TepVannak

**Comment by Fepvannak** [comment]
https://youtube.com/@TepVannak
