### ISSUE TITLE
Return the name of an Document 

### ISSUE THREAD

**Issue by simonweniger** [homanp/superagent#167]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

The endpoints `/documents` and `/documents/{documentId}` should also return the name of the document

### 📝 Additional Context

When we use the post endpoint for `/documents` we add a document name. But all get endpoints do not return it. 

Current response from the `/documents`  endpoint:
{
  "success": true,
  "data": [
    {
      "id": "clhnyae1t00016i2ixo0027c5",
      "userId": "clhj28u1300006ig02ptpm1sh",
      "user": {},
      "type": "PDF",
      "url": "https://digitalassets.tesla.com/tesla-contents/image/upload/IR/TSLA-Q1-2023-Update",
      "createdAt": "2023-05-14T21:50:59.349000+00:00",
      "updatedAt": "2023-05-14T21:50:59.349000+00:00",
      "index": null,
      "Agent": null
    } 
  ]
}

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
This was an issue with the documentation. Updated docs now. Thanks for reporting @simonweniger
