### ISSUE TITLE
Categorize Agents / Use superagent for different projects

### ISSUE THREAD

**Issue by simonweniger** [homanp/superagent#172]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

It would be helpful to be able to categorize agents by projects. I can see two scenarios where it makes managing agents simpler if they are categorized.

### Developers
Using superagent to build an app means that a lot of agents get created. Often times at least one agent per user. Now you maybe wanna have not only your user-created agents but also agents that are created by yourself. To be able to find them in the UI or get the right agent easily through an API call it would be nice to have each agent associated to a project. 

So a developer could fetch all agents from project xyz to display only those.

### NoCode users & Business use cases
Users who are using mostly the frontend to interact with superagent might use it in different teams, for different use cases or projects. But you mostly do not wanna create a new account for each project or use case. There a differentiation of agents by projects in the UI would make sense. 

It would also be helpful for future improvements of superagent for teams. Having projects allows to build a feature where you can invite other superagent users to a project to be able to update agens, documents and prompts.

### What changes are required

- [ ] New DB Table for projects (Name, id, members etc.)
- [ ] New field for projectId on the agents, documents, prompts, tools tables
- [ ] Update API calls to fetch by projectId
- [ ] Updated UI to show projects

### 📝 Additional Context

**Example of projects from vercel**
This is an example of how the UI for projects could look like. The user would select a project > Inside the project are all related agents, tools, documents and prompts. 

<img width="1512" alt="Bildschirm­foto 2023-07-08 um 11 10 00" src="https://github.com/homanp/superagent/assets/43147663/ff9f3993-e3c9-419f-9c3d-a94b0490871d">

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@simonweniger 100% agree. How would you Adapt the UI for this?

**Comment by homanp** [comment]
@simonweniger what do you think about adding tags instead of categories?

**Comment by simonweniger** [comment]
That sounds good! Do you think about adding a tags field with an array of tags to the agent?

**Comment by simonweniger** [comment]
@homanp It would be extremely helpful if I could add tags through an API call. With this feature, I could attach a userId from a user to the agent and then easily fetch information by tag userid. This would eliminate the need for me to store which user has which agent on my end. I believe many developers who create agents for their users would greatly benefit from this functionality.
