### ISSUE TITLE
Implement email confirmations for signup.

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#179]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should receive an email after they've created their account.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ankushbhardwxj** [comment]
Need more info on this. Do we want to use 3rd party email service to prepare templates and sending the emails ?

**Comment by homanp** [comment]
> Need more info on this. Do we want to use 3rd party email service to prepare templates and sending the emails ? 

Yes, I would like to use [resend.com](https://resend.com) or something that is OSS. 

The auth should be interested with NextAuth in the frontend and prisma in the backend.
