### ISSUE TITLE
Document is getting fetched in get documents even though there was an error while it was being embedded

### ISSUE THREAD

**Issue by shubham184** [homanp/superagent#184]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/homanp/superagent/labels/bug) didn't find any similar reports.

### Expected Behavior

Document should only be fetched by Get Documents if they were Indexed / embedded.

### Current behaviour

There was an error while Embedding the documents with vectorstore, still when I run the get documents api I am able to fetch all the document id and it is not possible to differentiate if a document was embedded or not.

### Steps to reproduce

1. Provide incorrect / missing details for vectorstore while post document api
2. when vectorstore.get_database.from_documents is being called stop the post api call
3. run api for get document you will notice a document was created

### Possible solution

Incase of error do not write to db

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [X] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@shubham184 would you be up for doing a PR for this?
