### ISSUE TITLE
Add ability to remove history or start new conversations with the same agent

### ISSUE THREAD

**Issue by ahnedeee** [homanp/superagent#186]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I think it would be a good feature to add the ability to reset chat history or make new conversations with the same agent

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@ahnedeee We have released something called sessions which allows you to do this without explicitly deleting memory. You can pass in a `session` key when you do a predict request to an agent to start a fresh memory!
