### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#189]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to reset password

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by ankushbhardwxj** [comment]
Ideal flow for this would be: 
- User clicks forget password on Login Screen
- Email is sent to user, with reset password link (validates the user)
- User resets password on the link previously sent
- User logs in using new password

Do let me know if this flow works, or would like to add anything.

**Comment by homanp** [comment]
> Ideal flow for this would be: 
> 
> - User clicks forget password on Login Screen
> 
> - Email is sent to user, with reset password link (validates the user)
> 
> - User resets password on the link previously sent
> 
> - User logs in using new password
> 
> 
> 
> Do let me know if this flow works, or would like to add anything. 

Works 100%

**Comment by homanp** [comment]
@ankushbhardwxj I will finish and merge the SSO PR today. Would mind having a look at this?

**Comment by ankushbhardwxj** [comment]
@homanp sure, I'll take this up. Can be assigned to me.

**Comment by ankushbhardwxj** [comment]
@homanp sure, I'll take this up. Can be assigned to me.

**Comment by homanp** [comment]
> @homanp sure, I'll take this up. Can be assigned to me.

Done, thanks!
