### ISSUE TITLE
Support SSO

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#190]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Superagent should support SSO

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by bdqfork** [comment]
We can set OPENAI_API_BASE env to using openai like server such as llama-cpp-python. I tested, it work well.

**Comment by homanp** [comment]
> We can set OPENAI_API_BASE env to using openai like server such as llama-cpp-python. I tested, it work well.

This issue is more about login/authentication

**Comment by bdqfork** [comment]
> > We can set OPENAI_API_BASE env to using openai like server such as llama-cpp-python. I tested, it work well.
> 
> This issue is more about login/authentication

I mixed it up with OSS, sorry about that.

**Comment by ankushbhardwxj** [comment]
Which platforms would we like to support for SSO ? Github & Gmail makes most sense to me.

**Comment by homanp** [comment]
> Which platforms would we like to support for SSO ? Github & Gmail makes most sense to me. 

Github, Google, Microsoft!

**Comment by homanp** [comment]
> Which platforms would we like to support for SSO ? Github & Gmail makes most sense to me. 

Also this should work with NextAuth on the frontend and Prisma schema on the backend! Is this something you could take a stan at @ankushbhardwxj

**Comment by ankushbhardwxj** [comment]
Yes, will take a shot at this. Can be assigned to me.

**Comment by homanp** [comment]
> Yes, will take a shot at this. Can be assigned to me. 

Done!
