### ISSUE TITLE
Add support for chatgpt plugins

### ISSUE THREAD

**Issue by dantheman0207** [homanp/superagent#210]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I wasn't able to access the linked *Ideas in Discussions* but did not see any existing work on this.

Excited about this as it makes it much easier to add arbitrary tools to agents using a standardized format.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
It's something we will add!

**Comment by dantheman0207** [comment]
Fixed the `poetry` issue! Used [this stackoverflow post](https://stackoverflow.com/questions/70003829/poetry-installed-but-poetry-command-not-found) to find the answer; had to add this line to my `~/.zshrc` (I'm on a Mac): `export PATH="$HOME/.local/bin:$PATH"`

**Comment by dantheman0207** [comment]
I've never worked with Prisma before, having a little trouble and would appreciate any insight you might have.

I added a `CHATGPT_PLUGIN` to the `ToolType` enum in the schema. It created a migration which looks identical to the migrations previously used to add other tool types. But when I try to create a chatgpt plugin tool (line 23 of `tools.py` in this branch) I get the following error:
```
prisma.errors.MissingRequiredValueError: Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneTool.data.ToolCreateInput.user`: A value is required but not set., Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Error parsing value: Enum value 'CHATGPT_PLUGIN' is invalid for enum type ToolType., Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Value types mismatch. Have: Scalar(String("CHATGPT_PLUGIN")), want: Null]]` at `Mutation.createOneTool.data`
```

This seems like the enum doesn't include this type, but maybe I'm misreading the error? Any thoughts @homanp ? I've tried recreating the database from scratch a couple times.

**Comment by homanp** [comment]
> I've never worked with Prisma before, having a little trouble and would appreciate any insight you might have.
> 
> 
> 
> I added a `CHATGPT_PLUGIN` to the `ToolType` enum in the schema. It created a migration which looks identical to the migrations previously used to add other tool types. But when I try to create a chatgpt plugin tool (line 23 of `tools.py` in this branch) I get the following error:
> 
> ```
> 
> prisma.errors.MissingRequiredValueError: Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneTool.data.ToolCreateInput.user`: A value is required but not set., Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Error parsing value: Enum value 'CHATGPT_PLUGIN' is invalid for enum type ToolType., Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Value types mismatch. Have: Scalar(String("CHATGPT_PLUGIN")), want: Null]]` at `Mutation.createOneTool.data`
> 
> ```
> 
> 
> 
> This seems like the enum doesn't include this type, but maybe I'm misreading the error? Any thoughts @homanp ? I've tried recreating the database from scratch a couple times.

Try regenerating the prisma client, e.g `prisma generate` this issue happens due to caching of some sort in prisma. It's not a bug in the migration or your code.

**Comment by dantheman0207** [comment]
> > I've never worked with Prisma before, having a little trouble and would appreciate any insight you might have.
> > I added a `CHATGPT_PLUGIN` to the `ToolType` enum in the schema. It created a migration which looks identical to the migrations previously used to add other tool types. But when I try to create a chatgpt plugin tool (line 23 of `tools.py` in this branch) I get the following error:
> > ```
> > 
> > prisma.errors.MissingRequiredValueError: Failed to validate the query: `Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneTool.data.ToolCreateInput.user`: A value is required but not set., Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Unable to match input value to any allowed input type for the field. Parse errors: [Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Error parsing value: Enum value 'CHATGPT_PLUGIN' is invalid for enum type ToolType., Query parsing/validation error at `Mutation.createOneTool.data.ToolUncheckedCreateInput.type`: Value types mismatch. Have: Scalar(String("CHATGPT_PLUGIN")), want: Null]]` at `Mutation.createOneTool.data`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This seems like the enum doesn't include this type, but maybe I'm misreading the error? Any thoughts @homanp ? I've tried recreating the database from scratch a couple times.
> 
> Try regenerating the prisma client, e.g `prisma generate` this issue happens due to caching of some sort in prisma. It's not a bug in the migration or your code.

Awesome, thank you! This fixed the issue.

**Comment by dantheman0207** [comment]
Seems to be working! I will push my changes and post some walkthroughs showing it working. Need to test with more plugins.
