### ISSUE TITLE
UI agent output doesn't wrap text correctly

### ISSUE THREAD

**Issue by dantheman0207** [homanp/superagent#216]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/homanp/superagent/labels/bug) didn't find any similar reports.

### Expected Behavior

Doesn't wrap the text output to keep it within the agent's "OUTPUT" column.

### Current behaviour

Just runs off screen to the right.
![Screenshot 2023-07-27 at 18 13 31](https://github.com/homanp/superagent/assets/1239724/93c0067e-62db-44a1-a1a1-f5f217c2007d)

### Steps to reproduce

Run agent, see output not wrapped within "OUTPUT" column. This is is Safari in Mac OS Sonoma (still in beta).

This does NOT happen in Chrome on the same device.

### Possible solution

Totally unsure. Not urgent but happy to provide more info around debugging.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@dantheman0207 thanks for reporting. Are you submitting a fix on this or should I?

**Comment by dantheman0207** [comment]
I am not very talented with frontend, I couldn't see any obvious cause but I might be missing something. I don't have the skills to propose a solution.

**Comment by homanp** [comment]
@dantheman0207 is this still an issue?

**Comment by homanp** [comment]
Should be fixed now!
