### ISSUE TITLE
Support Petals

### ISSUE THREAD

**Issue by Sharpz7** [homanp/superagent#220]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Super agent should support https://petals.dev/ by default and help bring users to petals, as the best way to give free users access to best-in-class OSS models.

### 📝 Additional Context

I envisage a system where directly from superagent.sh people can use petals and take advantage of this ecosystem.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
Hey @Sharpz7 would you be open to contributing this?

**Comment by Sharpz7** [comment]
I don't know if I personally have the time right now, but happy to keep it on the back-burner for later.
