### ISSUE TITLE
Add support for uploading documents directly from local machine

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#236]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add support for uploading documents directly from a users local machine to Superagent. 

When a user uploads a document we can store it on AWS S3 and then reference the S3 storage url when creating a Document object in the database.

Thus this will only require a frontend implementation of the upload. Should support multiple files as well for the chosen file type.

mid there is any prebuilt upload era for to use with NextJS I would be open to implementing it. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@ksiabani will take a look at this! 🙏

**Comment by homanp** [comment]
Fixed in #257

**Comment by abhay-ramesh** [comment]
Hello there,

I'd like to recommend trying out the `next-s3-uploader` package, which I created specifically for Next.js app directories. It simplifies the file upload process seamlessly.

You can explore the [documentation](https://next-s3-uploader.abhayramesh.com/) for comprehensive details. Should you encounter any challenges or have questions, don't hesitate to get in touch with me or open a GitHub issue [here](https://github.com/abhay-ramesh/next-s3-uploader/issues). I'm here to provide assistance and support.
