### ISSUE TITLE
Add Avatar Pictures to agent chats

### ISSUE THREAD

**Issue by mattrob333** [homanp/superagent#243]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

for custom persona agents, we need to be able to add an avatar as the persona for that bot. This would be seen in the chat thread as well as an avatar picture as a header when you share the agents to others with the share link.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@mattrob333 This is great. Will prioritize
