### ISSUE TITLE
Add chat history to share UI

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#284]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to see the chat history when selecting a session in the share chat UI

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by JinhuW** [comment]
Is there any timeline fo this feature? or any implementation guidance. I may can help with this feature

**Comment by homanp** [comment]
Hey, a contribution here would be great. Well basically you need to do one API request to the AgentMemory table and load the conversations in the UI. Should be pretty easy. Would appreciate your help on this @JinhuW.

You should fecth the AgentMemory for a specific session/agent pair here: https://github.com/homanp/superagent/blob/main/ui/app/share/page.js#L37

Also you would need to create a API for fetching AgentMemory similar to this: https://github.com/homanp/superagent/blob/main/app/api/agents.py#L67

I can help out if you need anything. Are you up for it? @JinhuW ?

**Comment by JinhuW** [comment]
Hi, I am willing to implement this. Just for curiosity. How do you want to fetch the conversation history by the id?  As i saw there is only a session id in the table which could be dynamic.

**Comment by JinhuW** [comment]
Sorry, I am still feeling confused.
Because the session doesn't tie to users here. Since chat history is private information, How could we how that chat history belongs to a specific user?

**Comment by JinhuW** [comment]
Correct me if I am wrong. My suggestion here is we can add another field here called "converstaion_id" to retrieve the historical converstaion.

**Comment by homanp** [comment]
The session is unique for each user. Each user can have multiple sessions. So no extra mapping needed.

**Comment by JinhuW** [comment]
How could you figure out the user to session mapping?

**Comment by JinhuW** [comment]
ok, i see. However it means these historical conversation can not be retrieved from another device and we may lost track of this this historical conversation and leave this chat history in the db forever.

**Comment by homanp** [comment]
Yes it does, any suggestions on how we could make this better?

**Comment by homanp** [comment]
Yes ok, but when you share your agent the users using it don't have accounts and thus no user IDs. That's why we store them on localstorage.

**Comment by JinhuW** [comment]
> Yes ok, but when you share your agent the users using it don't have accounts and thus no user IDs. That's why we store them on localstorage.

we still can keep the id in the localstorage and only save that user -> conversation id mapping when they login with account.
For all the memory without user id, we can run a cron job to delete them in 24hours.

**Comment by homanp** [comment]
> > Yes ok, but when you share your agent the users using it don't have accounts and thus no user IDs. That's why we store them on localstorage.
> 
> 
> 
> we still can keep the id in the localstorage and only save that user -> conversation id mapping when they login with account.
> 
> For all the memory without user id, we can run a cron job to delete them in 24hours.

Alright! Sounds like a plan

**Comment by JinhuW** [comment]
FYI, I will create an initial change before next Friday and ask for the initial review. Once the backend code looks good to you. I will go ahead and make the following changes in the UI.

**Comment by homanp** [comment]
Duplicate
