### ISSUE TITLE
`return_direct` the content of the `tool` output 

### ISSUE THREAD

**Issue by simjak** [homanp/superagent#292]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

`return_direct` the content of the `tool` output and not let agent to rephrase it

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by simjak** [comment]
<img width="1013" alt="image" src="https://github.com/homanp/superagent/assets/20096648/79aeea6b-de71-400c-a5a8-8ca774f352a7">

**Comment by homanp** [comment]
@simjak I'm adding this to the SDK and UI.

**Comment by simjak** [comment]
Thanks!

**Comment by homanp** [comment]
@simjak this is now deployed and live in the SDK if you update it.
