### ISSUE TITLE
Virtual Environment

### ISSUE THREAD

**Issue by thesushilsharma** [homanp/superagent#30]
![image](https://github.com/homanp/superagent/assets/58214222/1b513b9f-3a82-456c-8c35-0dedb7e2b97f)
somehow it is not installing dependencies. 

![image](https://github.com/homanp/superagent/assets/58214222/0079c946-c1f7-48df-bbce-7fd8c6f1ee2d)

If I add this 
```sh
   virtualenv venv
   source venv/bin/activate
   ```
then it is installing dependencies
![image](https://github.com/homanp/superagent/assets/58214222/0f3efdbd-ce1f-4146-930f-52820e084e07)

To run the project from the root directory
```sh
   uvicorn app.main:app --reload
   ```

**Comment by homanp** [comment]
Yes you need a virtual env to run it. Python >= 3.9. After that you do `poetry install`

**Comment by homanp** [comment]
I've added some notes to the `README` about this.
