### ISSUE TITLE
Uvicorn port alignment with docker

### ISSUE THREAD

**Issue by bbfred** [homanp/superagent#311]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/homanp/superagent/labels/bug) didn't find any similar reports.

### Expected Behavior

When running the api locally the setup.sh port should connect to port 8080 of the docker container.

### Current behaviour

Currently, try to connect to 8000

### Steps to reproduce

Run pgdb in docker and run the api locally with setup.sh

### Possible solution

change setup.sh to:
#!/bin/bash

# Create and activate the virtual environment
virtualenv venv
source venv/bin/activate

# Install dependencies using Poetry
poetry install

# Run Prisma migration
poetry run prisma migrate dev

# Start the application with auto-reload on port 8080
uvicorn app.main:app --host 127.0.0.1 --port 8080 --reload

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
Will take a look at this!

**Comment by homanp** [comment]
@bbfred please check this out #312 does this mitigate this issue?

**Comment by heresandyboy** [comment]
I think for this a change to [setup.sh](https://github.com/homanp/superagent/blob/main/setup.sh) is needed to set the port to 8080

Something like this: (added `--port 8080` at the end)

``` bash
#!/bin/bash

# Create and activate the virtual environment
virtualenv venv
source venv/bin/activate

# Install dependencies using Poetry
poetry install

# Run Prisma migration
poetry run prisma migrate dev

# Start the application with auto-reload
uvicorn app.main:app --reload --port 8080
```
