### ISSUE TITLE
Is it possible to integrate LangChain's built-in tools into superagent?

### ISSUE THREAD

**Issue by iceworld724** [homanp/superagent#319]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Is it possible to integrate LangChain's built-in tools into superagent?

Below is a list of the built-in tools provided by LangChain:
https://python.langchain.com/docs/integrations/tools/

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@iceworld724 yes this is possible. Since the agent executor is ran by langchain

**Comment by iceworld724** [comment]
> @iceworld724 yes this is possible. Since the agent executor is ran by langchain

Great! I'm looking forward to it. I need to use some of LangChain's built-in tools, especially PubmedQueryRun.

**Comment by homanp** [comment]
I'll see what I can do!

**Comment by homanp** [comment]
@iceworld724 Pubmed is now live.
