### ISSUE TITLE
Not returning result after `cache_ttl` > 0

### ISSUE THREAD

**Issue by simjak** [homanp/superagent#327]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/homanp/superagent/labels/bug) didn't find any similar reports.

### Expected Behavior

<img width="644" alt="image" src="https://github.com/homanp/superagent/assets/20096648/78b4389f-4bd7-416a-a755-a3e978136952">

### Current behaviour

Not return result with enable cache_ttl

### Steps to reproduce

Predict endpoint to with cache_ttl

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
This issue has been resolved @simjak
