### ISSUE TITLE
 http://superagent-ui:3000/_vercel/insights/script.js

### ISSUE THREAD

**Issue by zethereumGmail** [homanp/superagent#341]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/homanp/superagent/labels/bug) didn't find any similar reports.

### Expected Behavior

http://superagent-ui:3000/_vercel/insights/script.js

Just did fresh install using docker compose created an agent and when I try to view it I just get an error telling me to check my browsers error log and this is a 404 that kills the page load

### Current behaviour

http://superagent-ui:3000/_vercel/insights/script.js

Just did fresh install using docker compose created an agent and when I try to view it I just get an error telling me to check my browsers error log and this is a 404 that kills the page load

### Steps to reproduce

http://superagent-ui:3000/_vercel/insights/script.js

Just did fresh install using docker compose created an agent and when I try to view it I just get an error telling me to check my browsers error log and this is a 404 that kills the page load

### Possible solution

http://superagent-ui:3000/_vercel/insights/script.js

Just did fresh install using docker compose created an agent and when I try to view it I just get an error telling me to check my browsers error log and this is a 404 that kills the page load

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [X] Windows

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@zethereumGmail could you provide a screenahot of the browser `console`

**Comment by zethereumGmail** [comment]
![superagent-404](https://github.com/homanp/superagent/assets/69935809/1ee2f003-10ef-4485-857b-860b0a63296f)

**Comment by homanp** [comment]
This seems to be related to something else. I can't reproduce on my end though. We have some good docker people in our Discord you can ask. They have contributed this part.

**Comment by homanp** [comment]
@zethereumGmail we have release a new version of Superagent that is twice as performant as the previous version. Please checkout the README to get started!
