### ISSUE TITLE
Implementing Agent Protocol

### ISSUE THREAD

**Issue by hackgoofer** [homanp/superagent#354]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Have you considered adopting Agent Protocol? https://github.com/AI-Engineers-Foundation/agent-protocol

This is an interface independent protocol, that more and more agent developers are using.

AutoGPT Forge uses it:
https://github.com/Significant-Gravitas/Auto-GPT-Forge

GPT Engineer is interested in adopting it:
https://github.com/AntonOsika/gpt-engineer

### 📝 Additional Context

This protocol is owed by a non-profit organization, and does not have financial incentives. Doing this task will allow public benchmarking as well as a more unified interface for agent2agent communication/collaboration.
If you are interested in adopting and would like support or contact, you can reach out to: hackgoofer@gmail.com

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
> ### ⚠️ Please check that this feature request hasn't been suggested before.
> 
> - [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
> - [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.
> 
> ### 🔖 Feature description
> 
> Have you considered adopting Agent Protocol? https://github.com/AI-Engineers-Foundation/agent-protocol
> 
> 
> 
> This is an interface independent protocol, that more and more agent developers are using.
> 
> 
> 
> AutoGPT Forge uses it:
> 
> https://github.com/Significant-Gravitas/Auto-GPT-Forge
> 
> 
> 
> GPT Engineer is interested in adopting it:
> 
> https://github.com/AntonOsika/gpt-engineer
> 
> 
> 
> ### 📝 Additional Context
> 
> This protocol is owed by a non-profit organization, and does not have financial incentives. Doing this task will allow public benchmarking as well as a more unified interface for agent2agent communication/collaboration.
> 
> If you are interested in adopting and would like support or contact, you can reach out to: hackgoofer@gmail.com
> 
> ### Acknowledgements
> 
> - [X] My issue title is concise and descriptive.
> - [X] I have searched the existing issues to make sure this feature has not been requested yet.
> - [X] I have provided enough information for the maintainers to understand and evaluate this request.

Hey, yes been in talks with devs behind this initiative prior to the launch. Last I heard they were going to contribute that part into Superagent

**Comment by hackgoofer** [comment]
Awesome. Mind if I ask who it was and what the plan is? Agent Protocol V1.0 is planned for late Sept, I'd love to keep close contact with those who are working with it. We have a discord, just in case they need any support: https://discord.gg/TxDzUWab

**Comment by homanp** [comment]
> Awesome. Mind if I ask who it was and what the plan is? Agent Protocol V1.0 is planned for late Sept, I'd love to keep close contact with those who are working with it. We have a discord, just in case they need any support: https://discord.gg/TxDzUWab

the founder of E2B dev, plan was to implement but haven't heard anything since then. this was a couple of weeks back.
