### ISSUE TITLE
Support for Together.ai LLM API

### ISSUE THREAD

**Issue by shavster** [homanp/superagent#383]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Hi, could Superagent support togethe.ai for LLM's? 

Quote: Over 50 leading open-source Chat, Language, Code, and Image are models available through the Together Inference API. For these models, you pay just for what you use. Prices are per 1,000 tokens, including input and output tokens.

### 📝 Additional Context

Most of these models run on multi-A100 instances, and the company is well-funded by high-profile investors, including Nvidia.

One API to access all these open-source models would be awesome.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@shavster will look into it.
