### ISSUE TITLE
Bash script for starting all required services

### ISSUE THREAD

**Issue by thesushilsharma** [homanp/superagent#40]
## Getting Started

To get started with SuperAgent, follow these steps:

1. Clone the SuperAgent repository into a public GitHub repository or fork it from [https://github.com/homanp/superagent/fork](https://github.com/homanp/superagent/fork). If you plan to distribute the code, keep the source code public.

   ```sh


   git clone https://github.com/homanp/superagent.git
   ```

2. Set up your `.env` file.

   ```sh
   cp .env.example .env
   ```

   - Configure the environment variables according to your requirements.

3. To run the script, simply execute it using:
   ```sh
   bash setup.sh
   ```

You can save the script in a file, e.g., `setup.sh`, 
```sh
#!/bin/bash

# Create and activate the virtual environment
virtualenv venv
source venv/bin/activate

# Install dependencies using Poetry
poetry install

# Run Prisma migration
poetry run prisma migrate dev

# Start the application with auto-reload
uvicorn app.main:app --reload
```

This script streamlines the setup process by creating the virtual environment, installing dependencies, performing the Prisma migration, and starting the application with auto-reload. It helps ensure a consistent and efficient development environment for Python web applications.

**Comment by homanp** [comment]
@thesushilsharma great idea. Please add a PR with the `bash` script. Perhaps it should contain exports of the `env` variables as well.

**Comment by thesushilsharma** [comment]
I could include that, however, doing so would throw an error in the data migration procedure. 
![image](https://github.com/homanp/superagent/assets/58214222/d551488b-c00b-4563-8506-52aa2840d879)

**Comment by homanp** [comment]
> I could include that, however, doing so would throw an error in the data migration procedure. 
> 
> ![image](https://github.com/homanp/superagent/assets/58214222/d551488b-c00b-4563-8506-52aa2840d879)
> 
> 
> 
> Environment variables can be explicitly added by users before the script is launched.

Add the DATABASE_MIGRATION_URL env variable

**Comment by homanp** [comment]
> ## Getting Started
> To get started with SuperAgent, follow these steps:
> 
> 1. Clone the SuperAgent repository into a public GitHub repository or fork it from https://github.com/homanp/superagent/fork. If you plan to distribute the code, keep the source code public.
>    ```shell
>    git clone https://github.com/homanp/superagent.git
>    ```
> 2. Set up your `.env` file.
>    ```shell
>    cp .env.example .env
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    
>    * Configure the environment variables according to your requirements.
> 3. To run the script, simply execute it using:
>    ```shell
>    bash setup.sh
>    ```
> 
> You can save the script in a file, e.g., `setup.sh`,
> 
> ```shell
> #!/bin/bash
> 
> # Create and activate the virtual environment
> virtualenv venv
> source venv/bin/activate
> 
> # .env file into current shell session
> source .env
> 
> # Install dependencies using Poetry
> poetry install
> 
> # Run Prisma migration
> poetry run prisma migrate dev
> 
> # Start the application with auto-reload
> uvicorn app.main:app --reload
> ```
> 
> I can create PR for this script

PR would be welcome!
