### ISSUE TITLE
User Interface Disruption on Agent Detail Page with Short Screen Height

### ISSUE THREAD

**Issue by jinho-kim-osd** [homanp/superagent#404]
![image](https://github.com/homanp/superagent/assets/138539706/41445261-72a5-4dbc-9bf9-f3dd29fc9575)
### Description

On the agent detail page, there is a UI issue that occurs when the screen height is too short. Specifically, the "Update" button floats in an unusual position and a vertical line is cut off at the bottom.

### Steps to reproduce

1. Fix the "Update" Button: Ensure that the "Update" button stays in its intended position regardless of screen height.
2. Vertical Line Truncation: The vertical line should extend fully to the bottom of the screen even when the screen height is reduced

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
Fixed by #561
