### ISSUE TITLE
Be able to pull chat gpt and other plugins manifest files from git urls

### ISSUE THREAD

**Issue by Mark0025** [homanp/superagent#407]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

I think if we could be able to just upload the URL from a GitHub database for instance. 
- https://github.com/dannyp777/ChatGPT-AI-Plugin-Manifest-Lists/blob/main/list-ai-plugin-json.txt

Then we could then have an agent fetch a list of tools and what they do and respond back giving us options on which one we want to use. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
This is perfect! Problem might be that not all of them work outside of the context of ChatGPT. But I definetly agree with this.
