### ISSUE TITLE
hard to copy agent id from the agent api.   from gui

### ISSUE THREAD

**Issue by arwyn6969** [homanp/superagent#411]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

and also to have both that and api key ready to use agnt and an agent. thanks.

its jus really hard to grab and a copy button would be great

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@arwyn6969 this is now fixed
