### ISSUE TITLE
superagent-api doesn't start without langsmith api_key

### ISSUE THREAD

**Issue by ppokrovskii** [homanp/superagent#437]
### Description

superagent-api docker doesn't start due to missing LangSmith API key even though LangSmith API key is not marked as mandatory in .env file
`2023-10-01 07:13:39 Traceback (most recent call last): 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 209, in run 2023-10-01 07:13:39     self.sleep() 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 357, in sleep 2023-10-01 07:13:39     ready = select.select([self.PIPE[0]], [], [], 1.0) 2023-10-01 07:13:39             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld 2023-10-01 07:13:39     self.reap_workers() 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 525, in reap_workers 2023-10-01 07:13:39     raise HaltServer(reason, self.WORKER_BOOT_ERROR) 2023-10-01 07:13:39 gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3> 2023-10-01 07:13:39  2023-10-01 07:13:39 During handling of the above exception, another exception occurred: 2023-10-01 07:13:39  2023-10-01 07:13:39 Traceback (most recent call last): 2023-10-01 07:13:39   File "/app/.venv/bin/gunicorn", line 8, in <module> 2023-10-01 07:13:39     sys.exit(run()) 2023-10-01 07:13:39              ^^^^^ 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 67, in run 2023-10-01 07:13:39     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run() 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 231, in run 2023-10-01 07:13:39     super().run() 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 72, in run 2023-10-01 07:13:39     Arbiter(self).run() 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 229, in run 2023-10-01 07:13:39     self.halt(reason=inst.reason, exit_status=inst.exit_status) 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 342, in halt 2023-10-01 07:13:39     self.stop() 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 393, in stop 2023-10-01 07:13:39     time.sleep(0.1) 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 242, in handle_chld 2023-10-01 07:13:39     self.reap_workers() 2023-10-01 07:13:39   File "/app/.venv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 525, in reap_workers 2023-10-01 07:13:39     raise HaltServer(reason, self.WORKER_BOOT_ERROR) 2023-10-01 07:13:39 gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3> 

`

### Steps to reproduce

1. run 'docker-compose --env-file docker.env up --build -d'
2. try calling an api
3. open container logs and observe the error

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@ppokrovskii I investigated this. If you remove the following env vars it should work:

LANGCHAIN_TRACING_V2
LANGCHAIN_ENDPOINT
LANGSMITH_PROJECT_ID
LANGCHAIN_API_KEY

At least it does for me. Please check this and get back to me if it's still not working.
