### ISSUE TITLE
export langsmith traces (to .csv)

### ISSUE THREAD

**Issue by rawwerks** [homanp/superagent#446]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

the "trace" feature is amazing!

is it possible to export the traces (for example, to .csv)? if not, please consider this a feature request.

![image](https://github.com/homanp/superagent/assets/19483938/cfcbecf9-9b44-4286-8e42-c58d1266d294)

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@rawwerks there is an API endpoint for exporting that we have added. Currently we are only able to handle JSON. Hope that is ok for now.
