### ISSUE TITLE
[Feature] add relationship property to agent

### ISSUE THREAD

**Issue by deboboy** [homanp/superagent#450]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add a property to agent for relationships; to associate an agent to a higher level entity.

For example an agent can be related to ‘Team A’. Or related to ‘Company A’. Or a member of ‘Group A’.

This will also be useful when agents need to be granted permission to cloud services. In AWS this would mean that an agent would be added as an IAM user, then added to a group to be granted permission to appropriate AWS services; at the read or write level.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@deboboy I will start with adding tags to agents which could be used for this.

**Comment by bbfred** [comment]
As mentioned in discord I think a nice second step would be to aim to something similar to the schema below. If you want support on how we could implement it let me know.

generator client {
  provider  = "prisma-client-py"
  interface = "asyncio"
}

datasource db {
  provider          = "postgresql"
  url               = env("DATABASE_URL")
  shadowDatabaseUrl = env("DATABASE_SHADOW_URL")
}

enum LLMProvider {
  OPENAI
  AZURE_OPENAI
}

enum LLMModel {
  GPT_3_5_TURBO_16K_0613
  GPT_3_5_TURBO_0613
  GPT_4_0613
  GPT_4_32K_0613
}

enum ToolType {
  BROWSER
  BING_SEARCH
  REPLICATE
  WOLFRAM_ALPHA
  ZAPIER_NLA
  AGENT
  OPENAPI
  CHATGPT_PLUGIN
  METAPHOR
  PUBMED
  CODE_EXECUTOR
}

enum DatasourceType {
  TXT
  PDF
  CSV
  PPTX
  XLSX
  DOCX
  GOOGLE_DOC
  YOUTUBE
  GITHUB_REPOSITORY
  MARKDOWN
  WEBPAGE
  AIRTABLE
  STRIPE
  NOTION
  SITEMAP
  URL
  FUNCTION
}

enum DatasourceStatus {
  IN_PROGRESS
  DONE
  FAILED
}

model Organization {
  id       String   @id @default(uuid())
  name     String
  users    ApiUser[]
  projects Project[]
}

model Project {
  id             String        @id @default(uuid())
  name           String
  description    String?
  organizationId String
  organization   Organization  @relation(fields: [organizationId], references: [id])
  agents         Agent[]
  datasources    Datasource[]
  tools          Tool[]
  workflows      Workflow[]
}

model ApiUser {
  id             String       @id @default(uuid())
  token          String?
  email          String?      @db.Text
  createdAt      DateTime     @default(now())
  updatedAt      DateTime     @updatedAt
  organizationId String
  organization   Organization @relation(fields: [organizationId], references: [id])
}

model Agent {
  id             String            @id @default(uuid())
  name           String
  avatar         String?
  initialMessage String?           @db.Text()
  description    String            @default("Add a agent description...") @db.Text
  isActive       Boolean           @default(false)
  createdAt      DateTime          @default(now())
  updatedAt      DateTime          @updatedAt
  llms           AgentLLM[]
  llmModel       LLMModel          @default(GPT_3_5_TURBO_16K_0613)
  prompt         String?
  projectId String
  project   Project @relation(fields: [projectId], references: [id])
  datasources    AgentDatasource[]
  tools          AgentTool[]
  workflowSteps  WorkflowStep[]
}

model Datasource {
  id          String            @id @default(uuid())
  name        String
  content     String?           @db.Text()
  description String?
  url         String?
  type        DatasourceType
  projectId String
  project   Project @relation(fields: [projectId], references: [id])
  createdAt   DateTime          @default(now())
  updatedAt   DateTime          @updatedAt
  metadata    String?           @db.Text
  status      DatasourceStatus  @default(IN_PROGRESS)
  datasources AgentDatasource[]
}

model AgentDatasource {
  agentId      String
  datasourceId String
  agent        Agent      @relation(fields: [agentId], references: [id], onDelete: Cascade)
  datasource   Datasource @relation(fields: [datasourceId], references: [id])
  createdAt    DateTime   @default(now())
  updatedAt    DateTime   @updatedAt

  @@id([agentId, datasourceId])
}

model Tool {
  id           String      @id @default(uuid())
  name         String
  description  String
  type         ToolType
  returnDirect Boolean     @default(false)
  metadata     String      @db.Text
  createdAt    DateTime    @default(now())
  updatedAt    DateTime    @updatedAt
  projectId String
  project   Project @relation(fields: [projectId], references: [id])
  tools        AgentTool[]
}

model AgentTool {
  agentId   String
  toolId    String
  agent     Agent    @relation(fields: [agentId], references: [id], onDelete: Cascade)
  tool      Tool     @relation(fields: [toolId], references: [id])
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@id([agentId, toolId])
}

model LLM {
  id        String      @id @default(uuid())
  provider  LLMProvider @default(OPENAI)
  apiKey    String
  options   Json?
  agents    AgentLLM[]
  createdAt DateTime    @default(now())
  updatedAt DateTime    @updatedAt
  projectId String
  project   Project @relation(fields: [projectId], references: [id])
}

model AgentLLM {
  agentId   String
  llmId     String
  agent     Agent    @relation(fields: [agentId], references: [id], onDelete: Cascade)
  llm       LLM      @relation(fields: [llmId], references: [id])
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@id([agentId, llmId])
}

model Workflow {
  id          String         @id @default(uuid())
  name        String
  description String?
  createdAt   DateTime       @default(now())
  updatedAt   DateTime       @updatedAt
  steps       WorkflowStep[]
  projectId String
  project   Project @relation(fields: [projectId], references: [id])
}

model WorkflowStep {
  id         String   @id @default(uuid())
  order      Int
  workflowId String
  workflow   Workflow @relation(fields: [workflowId], references: [id])
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt
  input      String   @db.Text
  output     String   @db.Text
  agentId    String
  agent      Agent    @relation(fields: [agentId], references: [id])
}
