### ISSUE TITLE
agent "intro message" to start chat

### ISSUE THREAD

**Issue by rawwerks** [homanp/superagent#457]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

For certain agent use cases, it is helpful to have the agent/chatbot start the conversation. (As opposed to the user.)

The feature request is for the optional ability to give the agent an "intro message". This serves both the function of prompting the user, as well as initializing the LLM's chat context the same way for every use.

One example of a tool with this feature is Poe:

https://poe.com/create_bot

<img width="801" alt="image" src="https://github.com/homanp/superagent/assets/19483938/4e4cd015-3f53-4b9d-a5f9-7ae2b2aeb898">

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@rawwerks this is now added to the UI, SDKs and API

**Comment by rawwerks** [comment]
thank you so much! that was fast. can't wait to try it out.

**Comment by rawwerks** [comment]
@homanp - almost there, but not quite: the intro message works on the internal chat UX, but it is not displayed on the "share" UX `https://beta.superagent.sh/share/...`
