### ISSUE TITLE
How to use SuperAgent to work with the GPT4ALL LLM 

### ISSUE THREAD

**Issue by oceands** [homanp/superagent#46]
Hey, we I am currently working with @thesushilsharma and we are looking for ways to integrate the GPT4ALL LLM in order to use it as our native LLM instead of the one provided by OpenAI. Are there any methods existing at this stage which would allow us to achieve this?

**Comment by homanp** [comment]
> Hey, we I am currently working with @thesushilsharma and we are looking for ways to integrate the GPT4ALL LLM in order to use it as our native LLM instead of the one provided by OpenAI. Are there any methods existing at this stage which would allow us to achieve this?

Hi, there's always a way. I'll post documentation for it. Are you planning on running the model locally or in the cloud?

**Comment by oceands** [comment]
Both first locally then in the cloud :)

**Comment by homanp** [comment]
> Both first locally then in the cloud :)
> 
> 

Got it

**Comment by homanp** [comment]
@oceands I made a PR to show how to use GPT4All: https://github.com/homanp/superagent/pull/47
You can check out that branch and play with it. My experience is that it runs really slow and not fit to push to production. If you guys have any ideas on how to optimize this that would be great.
