### ISSUE TITLE
intro message not displayed in https://beta.superagent.sh/share/

### ISSUE THREAD

**Issue by rawwerks** [homanp/superagent#463]
### Description

re: https://github.com/homanp/superagent/issues/457 

the intro message works inside of `https://beta.superagent.sh/agents/`, but not in `https://beta.superagent.sh/share/`. i think the share UX needs to be updated to look for the intro message.

### Steps to reproduce

1. make an intro message for your agent `https://beta.superagent.sh/agents/`
2. share your agent `https://beta.superagent.sh/share/`
3. behold

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
Thanks will fix!

**Comment by rawwerks** [comment]
@homanp - while you are at it - i'm having the same issue with the embed code: 
![image](https://github.com/homanp/superagent/assets/19483938/21c36298-5fe5-4d30-94f3-1ff287dbb154)

that might require a callback to issue the intro message on page load.

**Comment by homanp** [comment]
@rawwerks this should now be fixed.
