### ISSUE TITLE
Add OpenBB as a Data Source to Superagent 

### ISSUE THREAD

**Issue by BirchGlobal** [homanp/superagent#472]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Requesting to integrate OpenBB's SDK into Superagent to provide real-time financial data as a data source. This would enable agents to access a wealth of financial data including equity, options, crypto, forex, and more.

### 📝 Additional Context

The addition of OpenBB as a data source can significantly enhance the capabilities of agents by folding in real-time data and insights. OpenBB's SDK is Python-friendly and its implementation can open new possibilities for analytics, reporting, and decision-making within Superagent.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@BirchGlobal I researched this and unfortunately `OpenBB` doesn't support Python 3.11 for some reason. Adding this would unfortunately break other dependencies. I will keep an eye out after their updates and implement this then.

**Comment by homanp** [comment]
`OpenBB` can now be run with custom functions on your local machine.
