### ISSUE TITLE
Adding Contributors Section in Readme.md 

### ISSUE THREAD

**Issue by mohitd404** [homanp/superagent#475]
### What piece of documentation is affected?

Why Contributors section:- A "Contributors" section in a repo gives credit to and acknowledges 
the people who have helped with the project, fosters a sense of community, and helps others
 know who to contact for questions or issues related to the project.

### What part(s) of the article would you like to see updated?

**Issue type**

- [✅] Docs/readme.md 

### Additional Information

@homanp @shuriken-bytes  If you were planning this issue kindly assign it to me! I would love to work on it ! Thank you !

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@mohitd404 would you mind adding?

**Comment by mohitd404** [comment]
> @mohitd404 would you mind adding?

I have added @homanp Kindly review !! Thank You !!
