### ISSUE TITLE
Add OSS option to LLMS.

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#493]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

OSS LLMs should not have access to tools if the underlying model doesn't support function calling.  So OSS LLMs can do Rag and Completion.

This could probably be done with LangChain or LlamaIndex. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by waywardspooky** [comment]
Does this mean Superagent we'll be able to specify our own locally or remotely run LLMs as alternatives to the current options OpenAI, and Azure. That would be an incredibly powerful feature for the ai community. 

Perhaps a suggestion, being able to specify a model running on a specific port for general chat, another model running on a specific port for math, one running on a different port for coding, etc would be one of the biggest leaps in usability for me and others I imagine as well.

**Comment by Mikemansour** [comment]
If we could just add an OpenAi API base URL it would be great

**Comment by homanp** [comment]
> If we could just add an OpenAi API base URL it would be great

Yes, will come after OSS LLMs.
