### ISSUE TITLE
Incomplete trace captured when using OpenAPI based tools

### ISSUE THREAD

**Issue by lit-in** [homanp/superagent#494]
### Description

When using OpenAPI based tool, the langsmith traces do not capture the SequentialChain(llm function chain+request_chain) steps that converts "input" -> API payload -> API output. The input to third-party APIs(ref: https://smith.langchain.com/public/76a58b85-193f-4eb7-ba40-747f0d5dd56e/r/d4517a75-fad4-42d2-9835-0c2d7bb1ed67) helps debug faster

### Steps to reproduce

Callback argument is not passed to `get_openapi_chain()` in the source code, so there is no way to patch the main agent with the OpenAPI chain
[Discord discussion](https://discord.com/channels/1110910277110743103/1111217275958218834/1168177504679362630)

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@lit-in we decided to implement an Open Source observability platform instead.
