### ISSUE TITLE
Add possibility to bring your own vectorDB to cloud ui

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#510]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to bring their own vector db to the Cloud UI. This should be configurable through the UI and API/SDK. 

Should have off-the-shelf support for `Pinecone`, `Weaviate`, `Qdrant` and `AstraDB`. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by elisalimli** [comment]
> A user should be able to bring their vector db to the Cloud UI. 

Please elaborate, you want to be able to add vector dbs other than Pinecone, Weaviate, Qdrant and AstraDB,

**Comment by homanp** [comment]
> > A user should be able to bring their vector db to the Cloud UI. 
> 
> 
> 
> Please elaborate, you want to be able to add vector dbs other than Pinecone, Weaviate, Qdrant and AstraDB,
> 
> 

Currently the vector db is at in .env. Instead we should create a new section in the UI similar to LLM where the user can configure the vector db the want to use. Only one vector sh is allowed
