### ISSUE TITLE
[WIP] - Heterogenous Cloud Deployment Strategy for Superagent API

### ISSUE THREAD

**Issue by priyanshu-sharma** [homanp/superagent#518]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Brief Repo Structure details - 

1. fern - legacy as well as new APIs documents (might need to expose this as a service on prod) Deployment, Service
2. libs/dockers/api - superagent's image (docker file in superagent's Dockerfile folder). power by guicorn (Deployment, Service)
3. libs/docker/mh - redis and motorhead configuration (Deployment, Service for motorhead) and (Stateless and Amazon ElastiCache for prod deployment).
4. libs/docker/pgdb - postgres and pgadmin related for configuring Database (Need to expose Stateless or Amazon RDS/etc for database and expose on service for pgadmin).
5. Superagents UI - Deployment as well as service required for exposing the superagent UI.
6. libs/embed - reactjs with chakra ui application can use deployment and service to serve this in different env. (https://github.com/homanp/superagent/pull/281)
7. libs/legacy/app - FastAPI Application needs deployment and Service
8. libs/legacy/embed/ - react js and chakra UI need a service and deployment. Replica of ( libs/embed )
9. libs/legacy/helm - already have a lot of helm chart utilize the same in k8s manifests.
10. libs/legacy/ui - Nextjs application for Library Dashboard (Need service and deployment)
11. libs/superagent/app - FastAPI App. (Deployment and Service)
12. libs/ui - Core UI (Deployment and Service) same as 5.

Deployment Flow - 

1. Select the heterogenous cloud machine/server based on the regions between different service provider. 
2. Finalize the number of environment that you want to keep for this api (ex. - Dev, Test, Stage, Prod).
3. Based on this create a cluster of these available machine for different environments. This can easily be achieved by writing Terraform Script.
4. Setup other utilities servers such as Vault (for keeping all the secret based on the env.), Consul (to store all the other key value pairs), Nomad (to carry out the all the day to day for each cluster), 
5. After setting up the cluster, its time to write some kubernetes components such as deployments, configmap, cronjob, and service 

For this application from the brief repo structure details we can see all the runnable components. We can separate them as follows: -

1. legacy_api - (Service, Deployment, Configmap, PgBouncer, Nginx, Metrics Exporter)
2.  superagent_api - (Service, Deployment, Configmap, PgBouncer, Nginx, Metrics Exporter)
3. Amazon Elasticache, Redis (stateless) for dev, testing, and stage.
4. Motorhead -  (Service, Deployment, Configmap, Metrics Exporter).
5. Amazon RDS, etc, pgsql (stateless) for dev, testing, and stage.
6. Pgadmin - Service on the Stateless or Deployment for RDS.
7. Core UI - (Service, Deployment, Configmap, Nginx, Metrics Exporter)
8. Legacy UI - (Service, Deployment, Configmap, Nginx, Metrics Exporter)
9. Embed UI - (Service, Deployment, Configmap, Nginx, Metrics Exporter)

Other than this - 

Prometheus Exporter, RabbitMQ / Amazon SQS, Kafka, etc deployment may be needed in case of external dependency.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@priyanshu-sharma thanks for this. Will read it through and get back you via DM.
