### ISSUE TITLE
Log traces by session id instead of agent id.

### ISSUE THREAD

**Issue by kranthi419** [homanp/superagent#554]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

session_id as trace_id is preferred as most interactions in production are performed by non-logged in users. 
User interaction across sessions is too much data over time.
![Screenshot 2023-12-06 at 2 52 34 PM](https://github.com/homanp/superagent/assets/67440130/4d98f473-01b7-4d0d-a3e0-86b47d206780)

Requirements:
trace's id -> session_id
trace's name -> agent name
user id -> logged in user name/id
metadata -> agent id + any callback handler metadata
timestamp -> created/last updated
![Screenshot_20231206_152956](https://github.com/homanp/superagent/assets/67440130/61ae2df9-ea32-48c9-83ac-0f33cbadc324)

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@kranthi419 I added the fixes, currently the trace name is still set to Assistant due to API not having access to the complete Agent object. Will fix this later on.
