### ISSUE TITLE
A user should be able to set the LLM parameters such as `temprature`, `max_tokens` etc.

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#557]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

TBD

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by bdqfork** [comment]
I am considering whether to treat these parameters as attributes of the agent or as attributes of a session. If it's a property of the session, it should be sufficient to store it on the frontend, typically in local storage, based on the sessionId. How do you see it?

**Comment by homanp** [comment]
> I am considering whether to treat these parameters as attributes of the agent or as attributes of a session. If it's a property of the session, it should be sufficient to store it on the frontend, typically in local storage, based on the sessionId. How do you see it?

This should be passed via the Agent IMO

**Comment by bdqfork** [comment]
> > I am considering whether to treat these parameters as attributes of the agent or as attributes of a session. If it's a property of the session, it should be sufficient to store it on the frontend, typically in local storage, based on the sessionId. How do you see it?
> 
> This should be passed via the Agent IMO

Currently, services are primarily provided by the agent, which will be shared or incorporated into a workflow. It might be more appropriate to include it in the agent's attributes. I am considering adding a JSON type field named llmOption in the agent record to document parameters such as stream, max_token, temperature, and memory_size.

**Comment by homanp** [comment]
@elisalimli this is already possible to do when configuring the LLM. But perhaps this should be an option in the Agent as well? I'm thinking on the agent/invoke perhaps. What are your thoughts?

**Comment by elisalimli** [comment]
> @elisalimli this is already possible to do when configuring the LLM. But perhaps this should be an option in the Agent as well? I'm thinking on the agent/invoke perhaps. What are your thoughts?

These parameters won't change quite often, right? So, I think we should store it in the database. We can pass the parameters to the agents/invoke API endpoint, but I don't think it is necessary.

**Comment by homanp** [comment]
It's already stored in the llm object. so no need to re-store it. question here is if we should expose them in agent invocation to make it more easy to manipulate.

**Comment by elisalimli** [comment]
> expose them in agent invocation

this sounds feasible.

**Comment by homanp** [comment]
> > expose them in agent invocation
> 
> this sounds feasible since the options stored in the LLM table, not the AgentLLM

Go for it
