### ISSUE TITLE
creating a session on load in the UI

### ISSUE THREAD

**Issue by kranthi419** [homanp/superagent#565]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

problem: Different users' interacting with share/embedded agent are all shown under single trace. (i.e: with empty session) with incorrect user id.
solution: Each user session to be it's own trace.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by surajgojanur** [comment]
Redo this the check and fill it to slove this issue
