### ISSUE TITLE
Add pagination to `Agens` and `Worflows` list views

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#583]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

We should add pagination to the `Agents` and `Workflows` list pages.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by RutamBhagat** [comment]
I would like to work on this

**Comment by homanp** [comment]
> I would like to work on this

Go for it!

**Comment by homanp** [comment]
> I would like to work on this

Please use this for ui:

https://ui.shadcn.com/docs/changelog#pagination

**Comment by RutamBhagat** [comment]
> 
> Please use this for ui:
> 
> https://ui.shadcn.com/docs/changelog#pagination

Sorry just saw this, actually ShadCN had another pagination component for data tables I have used it for this UI instead 
https://ui.shadcn.com/docs/components/data-table#reusable-components
would this work for now?
