### ISSUE TITLE
Add the possibility to delete a workflow. 

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#587]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should have the possibility to delete a workflow and corresponding steps by from within the workflow detail page.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@elisalimli Do you mind adding an option to delete a workflow in the workflow detail page?

**Comment by elisalimli** [comment]
@homanp I will start working on it soon.

**Comment by elisalimli** [comment]
https://github.com/homanp/superagent/pull/586/commits/bf474d17d6c2163a4f453d691184fb6fda409428
