### ISSUE TITLE
Docs - Running Superagent locally

### ISSUE THREAD

**Issue by elisalimli** [homanp/superagent#589]
### What piece of documentation is affected?

https://docs.superagent.sh/overview/deployments/runnning-locally#run-database-migrations

### What part(s) of the article would you like to see updated?

We should first start our local database before running migrations.

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by RutamBhagat** [comment]
I would like to work on this issue

**Comment by homanp** [comment]
> I would like to work on this issue

Go for it @RutamBhagat. Would be great if we could dockerize the whole setup of both the API and UI with provisioning of the two databases. UI requires supabase. What do you think?

**Comment by RutamBhagat** [comment]
> > I would like to work on this issue
> 
> Go for it @RutamBhagat. Would be great if we could dockerize the whole setup of both the API and UI with provisioning of the two databases. UI requires supabase. What do you think?

TBH I don't know much about docker yet, nor have I dockerized any apps, I'll try to learn more about docker first before contributing

**Comment by elisalimli** [comment]
@RutamBhagat can you please try to run supabase for both backend and ui on your local system?

**Comment by homanp** [comment]
Also @RutamBhagat feel free to contribute stuff you are interested in!

**Comment by RutamBhagat** [comment]
> @RutamBhagat can you please try to run supabase for both backend and ui on your local system?

I was following the docs for setting up superagent locally and was able to run Superagent API but I feel like the docs could have provided more clear instructions for the Superagent UI especialy for 
Step 5:-
![image](https://github.com/homanp/superagent/assets/72187009/76c475d3-5a89-4e3e-8aa3-f15109ed96bf)
 like where this query should be run
 
![image](https://github.com/homanp/superagent/assets/72187009/44662dad-5b7e-45c3-afdb-bc42da5c707a)

**Comment by elisalimli** [comment]
> like where this query should be run

in the SQL editor of supabase.

**Comment by elisalimli** [comment]
> there is no option to enable github oauth provider in supabase cli local studio

yes, you can't access the providers' page using UI. But if you go to $SUPABASE_STUDIO_URL/project/default/auth/providers

you can find the providers.


For me, the URL is:
http://127.0.0.1:54323/project/default/auth/providers

**Comment by RutamBhagat** [comment]
https://github.com/homanp/superagent/assets/72187009/b4a627d1-48ce-4e46-a630-e4cf7a64f0fc

I keep getting this error while setting up github oAuth
Failed to update auth configuration: undefined

**Comment by elisalimli** [comment]
> And I don't receive the sign-in link when trying to sign in using email locally

You can find the email in the local inbucket (supabase)
