### ISSUE TITLE
Wolfarm Alpha as a tool

### ISSUE THREAD

**Issue by vectorcrow** [homanp/superagent#59]
Wolfram Alpha makes all systematic knowledge immediately computable and accessible to everyone. 
https://www.wolframalpha.com/

**Comment by homanp** [comment]
> Wolfram Alpha makes all systematic knowledge immediately computable and accessible to everyone. https://www.wolframalpha.com/

This will be added 100%

**Comment by homanp** [comment]
@vectorcrow I'm working on getting this released this week. Have some refactoring work I'm doing and then switching to this.

**Comment by homanp** [comment]
@vectorcrow this is now live
