### ISSUE TITLE
Replace `LangchainAgent` with vanilla OpenAI function calling. 

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#595]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Since the LangchainAgent currently only runs OpenAI function calling we want to replace this with native OpenAI function calling using LiteLLM as documented here: https://docs.litellm.ai/docs/completion/function_call

We can keep Langchain implementations for tools, prompt etc. as is and only replace the completion. 

References: 

https://github.com/homanp/superagent/blob/main/libs/superagent/app/agents/langchain.py#L169

https://github.com/homanp/superagent/blob/main/libs/superagent/app/agents/langchain.py#L194

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@elisalimli comment if you have questions.

**Comment by filip-michalsky** [comment]
+1 - great addition to expand to more LLMs. 

https://huggingface.co/Nexusflow/NexusRaven-V2-13B

this dropped recently as outperforming GPT-4 on function calls (allegedly)

**Comment by homanp** [comment]
> +1 - great addition to expand to more LLMs.
> 
> https://huggingface.co/Nexusflow/NexusRaven-V2-13B
> 
> this dropped recently as outperforming GPT-4 on function calls (allegedly)

Will test this out.
