### ISSUE TITLE
discord link broken

### ISSUE THREAD

**Issue by TheSnowGuru** [homanp/superagent#600]
### Description

discord link broken

### Steps to reproduce

**discord link broken on homepage** 

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@TheSnowGuru where on the webpage is it broken? Thank you for noticing.

**Comment by homanp** [comment]
@TheSnowGuru closing since I can't reproduce.
