### ISSUE TITLE
Add pagination to Tools and Datasources list views 

### ISSUE THREAD

**Issue by elisalimli** [homanp/superagent#611]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Same as #583, but for /apis and /datasources pages. 

### 📝 Additional Context

.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by RutamBhagat** [comment]
I can do the UI part

**Comment by homanp** [comment]
@elisalimli go ahead and implement this!
