### ISSUE TITLE
OpenAPI Tool fails to read certain OpenAPI specs. 

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#622]
### Description

The OpenAPI tool doesn't always success in parsing an openapi spec (yaml). 

Example spec that fails: https://api.drymergeqa.com/test-openapi

### Steps to reproduce

1. Create an agent
2. Add a OpenAPI tool with the following schema: https://api.drymergeqa.com/test-openapi
3. Run the agent

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@elisalimli would you mind having a look at this? 

The issue currently is that some OpenAPI specs don't work with the `LangChain` openapi agent/chain. Perhaps there is a better way to do this. Please research and fix this isssue!

**Comment by elisalimli** [comment]
I think OpenAPI Tool's failing to read certain OpenAPI specs is an intended implementation by langchain. The current implementation can call the endpoints derived from the given openapi spec.  

Closing this issue for now.
