### ISSUE TITLE
UI module not starting up due to missing seed data

### ISSUE THREAD

**Issue by tsukhu** [homanp/superagent#634]
### Description

while trying to setup the superagent platform we get the following error

![Screenshot 2024-01-03 at 1 12 47 PM](https://github.com/homanp/superagent/assets/846306/97645edf-e3be-4982-8a28-b8f6270e8c06)

### Steps to reproduce

Able to successfully setup the back and frontend based on the youtube tutorials and following https://github.com/homanp/superagent/blob/main/fern/mdx/deploy/local.mdx
-  Setup supabase
-  Setup pincone
-  Update .envs ui and backend
-  Prisma generate in backend folder
-  Start backend with uvicorn app.main:app —reload
- setup supabase auth with github https://supabase.com/docs/guides/auth/social-login/auth-github
- The UI starts properly and we are able to login via github
- The supabase db push sets up the tables correctly but since there is no data it is throwing the above mentioned error

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
Hi there, you need the backend running in order for the ui to work. The UI/API require two separate DBs. Here is a full guide:

https://docs.superagent.sh/overview/deployments/runnning-locally

**Comment by tsukhu** [comment]
Thank you @homanp  - I realize that now.

**Comment by homanp** [comment]
@tsukhu happy to help! Please join or Discord if you need further assistance!
