### ISSUE TITLE
Upload file shows error when configuring Pinecone as vector embedding database

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#648]
### Description

Upload file shows error when configuring Pinecone as vector embedding database gives the following error: 

```
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='superagent-v2-unknown.svc.https', port=443): Max retries exceeded with url: //superagent-v2-9c9daa7.svc.asia-southeast1-gcp.pinecone.io.pinecone.io/describe_index_stats (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x153741810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

### Steps to reproduce

1. Configue Pinecone in the UI
2. Add a new datasource

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by elisalimli** [comment]
@homanp is this still an issue?

**Comment by rapidstartup** [comment]
We fixed it in our install![Screenshot_20240121-222716.png](https://github.com/homanp/superagent/assets/59274825/cd7f41d3-add7-4fe8-8cc1-5b9b4ffe0251)

Let me know if you need a hand. The upload still works, but obv if you pushed that with the API it would return fail instead of the id

**Comment by elisalimli** [comment]
@rapidstartup that's great!

@homanp weren't you passing the pinecone index name in your case?

**Comment by homanp** [comment]
> @rapidstartup that's great!
> 
> 
> 
> @homanp weren't you passing the pinecone index name in your case?

Hey! Yes still an issue.

**Comment by homanp** [comment]
> @rapidstartup that's great!
> 
> @homanp weren't you passing the pinecone index name in your case?

I was passing, it works for me as inteneded.
