### ISSUE TITLE
Cannot delete an agent that is connected to a workflow. 

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#652]
### Description

Deleting an agent connected to a worflow throws foreign key constraint error. 

### Steps to reproduce

1. Connect an agent to a workflow
2. Try to delete agent

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@elisalimli would you mind having a look at this?

**Comment by elisalimli** [comment]
@homanp isn't this expected? Maybe we can show an error to the user "Make sure to delete your agent from the workflow before deleting it"

**Comment by homanp** [comment]
> @homanp isn't this expected? Maybe we can show an error to the user "Make sure to delete your agent from the workflow before deleting it" 

Perhaps we should remove the workflow step that includes the agent?

**Comment by elisalimli** [comment]
> > @homanp isn't this expected? Maybe we can show an error to the user "Make sure to delete your agent from the workflow before deleting it"
> 
> Perhaps we should remove the workflow step that includes the agent?

Yeah, we can add `on delete cascade` to automatically delete when the agent is deleted.
 Or show a warning to the user and tell him/her to delete them, then delete the agent

**Comment by homanp** [comment]
> > > @homanp isn't this expected? Maybe we can show an error to the user "Make sure to delete your agent from the workflow before deleting it"
> > 
> > 
> > Perhaps we should remove the workflow step that includes the agent?
> 
> Yeah, we can add `on delete cascade` to automatically delete when the agent is deleted. Or show a warning to the user and tell him/her to delete them, then delete the agent

Add cascade
