### ISSUE TITLE
Add http status to the segment logs

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#658]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

We want to be able to see which requests passed and which request failed to the `agent/invoke` endpoint. the https status code should be passed to the Segment tracking together with the assistants details. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@elisalimli can you have a look at this please

**Comment by elisalimli** [comment]
Fixed by #662
