### ISSUE TITLE
Pass used tokens and cost to Segment Inoke Agent event

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#661]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

LangChain passes tokens used and cost in the agent callback. Aggregate these values for each invocation and pass to Segment `Invoked Agent` event.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@elisalimli can you take a look at this?

**Comment by elisalimli** [comment]
@homanp We can't get the usage parameters if the streaming is enabled. Is it ok for us if we pass the cost parameters if the streaming is not enabled?

Reference:
https://github.com/langchain-ai/langchain/issues/3114#issuecomment-1695705394

**Comment by elisalimli** [comment]
> > @homanp We can't get the usage parameters if the streaming is enabled. Is it ok for us if we pass the cost parameters if the streaming is not enabled?
> > Reference:
> > [langchain-ai/langchain#3114 (comment)](https://github.com/langchain-ai/langchain/issues/3114#issuecomment-1695705394)
> 
> So only when streaming is enabled?

Yeah, the usage, cost parameters is only returned when streaming is *disabled*

**Comment by homanp** [comment]
Wondering if there is some way for us to count tokens ourselves @elisalimli I'm pretty sure this is what LiteLLM does.

**Comment by elisalimli** [comment]
Yeah! 

https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken

We can count it and return an approximate cost price.

**Comment by homanp** [comment]
@elisalimli let's do that, please have a look at how LiteLLM does it. They have count for every LLM.
