### ISSUE TITLE
Return itermediate steps when streaming response

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#665]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Return the intermediate steps in the stream to the client.
Langchain should have this built in, basically reporting back when a `Tool` is being used. Please return these in the streaming response of an Agent.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by elisalimli** [comment]
@homanp aren't we already doing that? 

https://github.com/homanp/superagent/blob/main/libs/superagent/app/api/agents.py#L272-L282

**Comment by elisalimli** [comment]
@homanp I'm closing this then
