### ISSUE TITLE
Browser Agent

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#70]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Create a browser agent that can search the web and aggregate content. 

This could be followed up with controlling the browser in future PRs. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by lightningRalf** [comment]
maybe something like this could help?
 https://github.com/Josh-XT/AGiXT/blob/main/agixt/extensions/searxng.py
