### ISSUE TITLE
Fix Markdown editor for Workflow steps

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#711]
### Description

The Markdown seems corrupted when passing the output to the client. 

<img width="1094" alt="Screenshot 2024-01-28 at 14 33 22" src="https://github.com/homanp/superagent/assets/2464556/e02ab8e2-41fa-4515-97eb-1a08f32f4440">

Please fix this by branching of `feat/workflow-refactor` with `git checkout -b my_fix feat/workflow-refactor`

### Steps to reproduce

n/a

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@elisalimli please fix this next

**Comment by elisalimli** [comment]
This issue can't be reproduced.
