### ISSUE TITLE
Expose more LLM options.

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#72]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Users want to be able to control settings such as `max_tokens`, `temperature` etc. 

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by revskill10** [comment]
Also need to specify openai_url if user wants to use local version of OpenAI.

**Comment by bdqfork** [comment]
I want to add params  `max_tokens`, `temperature ` and `memory size`  to agent predict api. What do you think @homanp ? If ok, I will make PR soon.

**Comment by homanp** [comment]
> I want to add params  `max_tokens`, `temperature ` and `memory size`  to agent predict api. What do you think @homanp ? If ok, I will make PR soon.

Perfect, Please add in a PR!
