### ISSUE TITLE
BigQuery logs not being fetched correctly

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#763]
### Description

The BigQuery logs for agents are not being fetched correctly.

### Steps to reproduce

n/a

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by bdqfork** [comment]
Could support using ClickHouse logs?

**Comment by homanp** [comment]
Yep, we have some issues with BigQuery rn but after resolving that we will add OpenLLMetry for logs so you can export.
