### ISSUE TITLE
Show tool usage for each step in a workflow.

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#791]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

We should show tool usage for each step in a workflow separately in a list.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by homanp** [comment]
@elisalimli can we add function callback to each step in a workflow in the UI

**Comment by elisalimli** [comment]
> @elisalimli can we add function callback to each step in a workflow in the UI

Sure, we need to specify the step name
