### ISSUE TITLE
Running invoke after saving input fails

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#843]
### Description

This issue is reported by a user. 

See error below:

```
  File "/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/workflows.py", line 192, in invoke
    workflow_step.agent.metadata.get("model")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

### Steps to reproduce

Issue seems to be happening after saving multiple times. 

### Acknowledgements

- [X] My issue title is concise, descriptive.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of superagent.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by homanp** [comment]
@elisalimli can you have a look at this please.

**Comment by rapidstartup** [comment]
Is this why the stock tracker template doesn't work? Invoke creates a successful 200 but then nothing else seems to happen. Let me know if you need me to provide further details, been trying to fix this for 2 days

**Comment by homanp** [comment]
> Is this why the stock tracker template doesn't work? Invoke creates a successful 200 but then nothing else seems to happen. Let me know if you need me to provide further details, been trying to fix this for 2 days

No! This is actually another issue. I can have a looks at the stock template. Also you should checkout [vip.superagent.sh](https://vip.superagent.h). 

I will take a look at the stock template see what the issue can be. 

Do you have any errors to share?

**Comment by alanzabihi** [comment]
@rapidstartup let us help you: https://vip.superagent.sh/apply

**Comment by rapidstartup** [comment]
Thanks. It doesn't even work on your demo site anymore. Was offering to help fix :)

**Comment by homanp** [comment]
> Thanks. It doesn't even work on your demo site anymore. Was offering to help fix :)

Oh! Would be great if could help us with that. I'm in the process of creating new templates with auth etc.
