### ISSUE TITLE
Add support for Llamaindex

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#87]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Add support for pulling in Llamaindex into Superagent.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by lightningRalf** [comment]
```
It's now possible to use DocArray vector stores in Llama Index 🦙  They're super easy to use! 🚀  

Make sure to check out these docs to learn more about how to use them:
https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/DocArrayInMemoryIndexDemo.html
https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/DocArrayHnswIndexDemo.html
```
Added here for context

**Comment by lightningRalf** [comment]
This could help with implementation:
https://twitter.com/matchaman11/status/1669368122048954370
