### ISSUE TITLE
Add possiblity to add multiple documents and tools as context to a LLM

### ISSUE THREAD

**Issue by homanp** [homanp/superagent#89]
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to add multiple documents to an Agent.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

**Comment by lightningRalf** [comment]
Is this something for the llama index and their document loaders? Should be easier to build as from scratch, or do you wanna stick with strictly langchain and their document loaders?

**Comment by homanp** [comment]
> Is this something for the llama index and their document loaders? Should be easier to build as from scratch, or do you wanna stick with strictly langchain and their document loaders?

I'm open to any solution, LangChain not a requirement.
